# Generated by Django 3.1.4 on 2020-12-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aeronave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('max_marcianos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nave_nodriza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_revisor', models.CharField(max_length=400)),
                ('num_pasajeros', models.IntegerField()),
                ('fecha_revision', models.DateField()),
                ('aeronave_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisa_a', to='marcianos.aeronave')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('aeronave_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subido_en', to='marcianos.aeronave')),
            ],
        ),
        migrations.AddField(
            model_name='aeronave',
            name='nave_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nave_destino', to='marcianos.nave_nodriza'),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='nave_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nave_origen', to='marcianos.nave_nodriza'),
        ),
    ]
