# Generated by Django 3.1.4 on 2020-12-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='pasajeros',
            field=models.ManyToManyField(to='marcianos.Pasajero'),
        ),
    ]
