# Generated by Django 3.1.4 on 2020-12-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nave_nodriza',
            table='object_list',
        ),
    ]
