# Generated by Django 3.1.4 on 2020-12-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0002_auto_20201209_2108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nave_nodriza',
            table=None,
        ),
    ]
