# Generated by Django 3.1.4 on 2020-12-09 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0003_auto_20201209_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='aeronave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('max_marcianos', models.IntegerField()),
                ('nave_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcianos.nave_nodriza')),
            ],
        ),
    ]
