# Generated by Django 3.1.4 on 2020-12-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0004_aeronave'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='nave_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nave_destino', to='marcianos.nave_nodriza'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='nave_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nave_origen', to='marcianos.nave_nodriza'),
        ),
    ]
