# Generated by Django 3.1.3 on 2020-12-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0005_auto_20201209_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('aeronave_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subido_en', to='marcianos.aeronave')),
            ],
        ),
    ]
