# Generated by Django 3.1.4 on 2020-12-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0007_auto_20201219_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='pasajeros',
            field=models.ManyToManyField(to='marcianos.Pasajero'),
        ),
    ]
