# Generated by Django 3.1.3 on 2020-12-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0007_auto_20201212_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronave',
            name='max_marcianos',
            field=models.PositiveIntegerField(),
        ),
    ]
