# Generated by Django 3.1.3 on 2020-12-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0009_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
