# Generated by Django 3.1.3 on 2020-12-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0010_aeronave_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeronave',
            name='full',
        ),
        migrations.AddField(
            model_name='aeronave',
            name='marcianos_count',
            field=models.IntegerField(default=0),
        ),
    ]
