# Generated by Django 3.1.3 on 2020-12-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcianos', '0011_auto_20201218_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeronave',
            name='marcianos_count',
        ),
    ]
